install.packages("foreign")
library(foreign)
# list.files("/r/data/MEPS")
setwd("/r/data/MEPS")
list.files()
unzip("h181ssp.zip")
df = read.xport("h181.ssp")
write.csv(df, file="h181.csv", row.names=FALSE, quote=FALSE)
file.remove("h181.zip")
